@echo off
setx JAVA_ISSUER "WRITE YOUR ISSUER"
setx JAVA_SECRETKEY "WRITE YOUR SECRETKEY"
setx DB_NAME "WRITE YOUR DB NAME"
setx DB_URL "WRITE YOUR DB URL"
setx DB_USERNAME "WRITE YOUR DB USERNAME"
setx DB_PASSWORD "WRITE YOUR DB PASSWORD"
setx GIT_USERNAME "WRITE YOUR GIT USERNAME"
setx GIT_CONFIG_PROJECT "https://github.com/(GIT_USERNAME)/(PROJECT_NAME).git"
setx GIT_TOKEN_KEY "WRITE YOUR TOKEN"

