package com.aligunes;

public enum EDers {
    TURKCE,
    MATEMATIK,
    HAYAT_BILGISI,
    GORSEL_SANATLAR,
    MUZIK,
    BEDEN,
    SERBEST_ETKINLIK,
    YABANCI_DIL,
    FEN_BILIMLERI,
    SOSYAL_BILGILER,
    DIN,
    TRAFIK,
    INSAN_HAKLARI,
    BILISIM_TEKNOLOJILERI,
    TEKNOLOJI_TASARIM,
    REHBERLIK,
    INKILAP_TARIHI_VE_ATATURKCULUK;

}

