server:
  port: 80
  error:
    whitelabel:
      enabled: false

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  cloud:
    gateway:
#      httpclient:
#        ssl:
#          use-insecure-trust-manager: true
      default-filters:
        - RewritePath=/(?<segment>.*), /$\{segment}
      routes:
        - id: error-route
          uri: forward:/error.html
          predicates:
            - Path=/error/**
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth
                fallbackUri: forward:/fallback/auth
        - id: product-service
          uri: http://localhost:9091
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: product
                fallbackUri: forward:/fallback/product
        - id: sale-service
          uri: http://localhost:9092
          predicates:
            - Path=/sale/**
          filters:
            - name: CircuitBreaker
              args:
                name: sale
                fallbackUri: forward:/fallback/sale
        - id: user-profile-service
          uri: http://localhost:9093
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user
                fallbackUri: forward:/fallback/user