#server:
#  port: 8080

#spring:
# datasource:
#   username: postgres
#   password: 123456789
#   url: jdbc:postgresql://localhost:5432/blogdb
#   driver-class-name: org.postgresql.Driver

# jpa:
#  show-sql: true
#  hibernate:
#   ddl-auto: create